### ISSUE TITLE
【bug】JsToTempString无法获取WkeJsBindFunction回调参数

### ISSUE THREAD

**Issue by CodeNeedWho** [suiyunonghen/GVCL#2]
用最新的miniblink测试的，无法的到参数

**Comment by suiyunonghen** [comment]
> 
> 
> 用最新的miniblink测试的，无法的到参数

你是怎么用的？我绑定的位置不是已经处理好了相关的处理代码吗？在wrapBindFuncs中，对于参数的处理在JSValue2Interface

**Comment by CodeNeedWho** [comment]
代码如下：
`func wrapBindFuncs(es gminiblink.JSExecState, param uintptr) gminiblink.JSValue {
	paramCount := gminiblink.BlinkLib.JsArgCount(es)

	for i := 0; i < paramCount; i++ {
		jsv := gminiblink.BlinkLib.JsArg(es, i)
		content := gminiblink.BlinkLib.JsToString(es, jsv)
		fmt.Println("js参数：", content)
	}
	return gminiblink.BlinkLib.JsUndefined()
}`
`gminiblink.BlinkLib.WkeJsBindFunction("GoMsgBox", wrapBindFuncs, 0, uint(3))`

**Comment by CodeNeedWho** [comment]
```
func wrapBindFuncs(es gminiblink.JSExecState, param uintptr) gminiblink.JSValue {
	paramCount := gminiblink.BlinkLib.JsArgCount(es)

	for i := 0; i < paramCount; i++ {
		jsv := gminiblink.BlinkLib.JsArg(es, i)
		content := gminiblink.BlinkLib.JsToString(es, jsv)
		fmt.Println("js参数：", content)
	}
	return gminiblink.BlinkLib.JsUndefined()
}
gminiblink.BlinkLib.WkeJsBindFunction("GoMsgBox", wrapBindFuncs, 0, uint(3))
```

**Comment by CodeNeedWho** [comment]
再次测试发现，用64位的，并且版本为1.13.1的就可以= =！

**Comment by suiyunonghen** [comment]
> 
> 
> 再次测试发现，用64位的，并且版本为1.13.1的就可以= =！

额，这个就不知道了，不过，这个Go的版本，确实是存在一些问题的，暂时还没找到解决方案，就是miniblink本身默认调用方式都是cdecl，而使用Go这个默认好像是stdcall，所以获取有些参数确实是有点问题，我当时测试过，当你传递多个参数的时候，第一个获取的不对，然后第二个，第三个，后面的又是对的。

**Comment by suiyunonghen** [comment]
> 
> 
> 非常感谢，请问你用node.dll，是自己编译的嘛，jsToString是否需要自己改动一下呢

是从作者的Q群中下载的一个64位版本的。

**Comment by CodeNeedWho** [comment]
好的= =
